### ISSUE TITLE
Protocol Browser - 404 on all resources

### ISSUE THREAD

**Issue by theduke** [ChromeDevTools/devtools-protocol#79] opened 2018-01-18 15:32 UTC
The browser currently shows only 404s for all resources, inlcuding head, stable1.2 and stable1.3:

https://chromedevtools.github.io/devtools-protocol/

Is there any other resource for how the protocol looks like?

**Comment by kdzwinel** [comment] 2018-01-18 15:49
I can't reproduce it. Can you please let us know what browser you are using?

**Comment by kdzwinel** [comment] 2018-01-18 15:51
Moving to protocol viewer repo: https://github.com/ChromeDevTools/debugger-protocol-viewer/issues/100

**Closed by kdzwinel** 2018-01-18 15:51 UTC
