### ISSUE TITLE
Scripts are not loaded after using Page.setDocumentContent

### ISSUE THREAD

**Issue by utkuturunc** [ChromeDevTools/devtools-protocol#13] opened 2017-05-02 08:09 UTC
I am trying to pass a html file as string instead of navigating to an url. I followed the comment from this url: https://github.com/cyrus-and/chrome-remote-interface/issues/95

Page.setDocumentContent sets the html content and loads the needed css files but javascript files are not loaded (cannot see them in the sources tab of the devtools)

**Comment by westy92** [comment] 2017-07-17 14:50
Is there any information available for this issue?

**Comment by kensoh** [comment] 2017-07-17 15:11
Thanks @westy92 for bumping, I've subscribed to this thread and also interested to know how to handle such a use case.

**Comment by paulirish** [comment] 2017-07-17 17:23
First I'll show you how I normally investigate questions like this, with `DOM.setOuterHTML` as an example. Someone (issue #29) was wondering why it didn't have the same behavior as a normal `documentElement.outerHTML = ...` call. 

1. Go to https://cs.chromium.org/
2. Search for `setOuterHTML -f:out -f:test`
  - The `-f:out -f:test` avoids generated files and tests.
  - This search ends up showing a few results, some in the declarative protocol.json, some within Blink's implementation of `Element` and a few in `core/inspector` (the devtools backend): 
![image](https://user-images.githubusercontent.com/39191/28279981-20653b50-6ad7-11e7-81f3-ab663c05bca7.png)
3. Click through to the most likely implementation. All protocol methods are backed by a "Inspector____Agent", so that's usually your best bet.
4. Immediately I see something pretty interesting: 
![image](https://user-images.githubusercontent.com/39191/28280012-366dfde2-6ad7-11e7-87e1-e795dd58153c.png)
5. This  method is using `dom_patch_support.PatchDocument(outer_html);` which sounds a little more complicated than just plainly setting the document HTML. Indeed, it is doing a kind of virtual-DOM diff-match-patch change to the DOM, where nodes that shouldn't change don't.


So that's the basic technique. 

-------


For this issue, I follow the lead to [`Document::SetContent`](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/dom/Document.cpp?type=cs&q=f:document.cpp+setContent%5C%28) which looks totally normal.

After clicking around a bit and scratching my head I [git blame](https://chromium.googlesource.com/chromium/src/+blame/1d441d93779f4e81634c48119c542559d1155603/third_party/WebKit/Source/core/inspector/InspectorPageAgent.cpp) and find out that this method was changed just 9 days ago: https://chromium.googlesource.com/chromium/src/+/7299ed5a97695accbb5b04e269ac05ec9366d30b%5E%21/#F4

And what do you know, before this commit, the `setDocumentContent` method was using that same DOMPatchSupport stuff. :)

So as of crrev/485113, it's using the real blink `Document::SetContent` where I expect scripts are evaluated, but previous to that I would expect scripts to not be re-evaluated on these calls.

Does that match up with what you're seeing?

**Comment by kensoh** [comment] 2017-07-17 17:30
Thanks @paulirish , followed your tutorial and saved the page for reference! :smile:

**Comment by westy92** [comment] 2017-07-26 01:26
Thanks, @paulirish!  How can you tell if the mentioned commit (https://chromium.googlesource.com/chromium/src/+/7299ed5a97695accbb5b04e269ac05ec9366d30b%5E%21/#F4) ended up in a Chrome release?  Do you just pull up the log (https://chromium.googlesource.com/chromium/src/+log/59.0.3071.115..60.0.3112.78?pretty=fuller&n=10000) and search for that commit hash?  If so, I'm not seeing it.

**Comment by paulirish** [comment] 2017-07-26 01:34
@westy92 good question.

Find the chromium rev number and you'll plug that into the "Find releases" form field on https://omahaproxy.appspot.com/

More details: https://www.chromium.org/blink/when-will-a-fix-ship-in-chrome-stable-or-canary#TOC-Not-on-Chromestatus-

**Comment by tommymonk** [comment] 2018-03-26 14:43
It seems the aforementioned commit never got merged ?

**Comment by westy92** [comment] 2018-03-26 16:48
Using the methods described above, it looks like the fix landed in 61.0.3153.0.

I can confirm `Page.setDocumentContent()` is now loading scripts because I'm using it [here](https://github.com/westy92/html-pdf-chrome/blob/master/src/index.ts#L78) and it is tested [here](https://github.com/westy92/html-pdf-chrome/blob/master/test/index.ts#L196-L214).

**Comment by tommymonk** [comment] 2018-03-27 09:31
Thanks @westy92, my mistake I think, I'm creating a new Page with "about:blank" and trying to set html using Page.setDocumentContent()

The css/javascript weren't being downloaded but I've realized the URLs are relative and the page I'm loading into is "about:blank".

I'm not sure if there's a solution ?

**Comment by abadraja** [comment] 2019-01-24 17:57
@tommymonk Could you resolve it?
 Can you send a sample of your code? I'm getting the same error trying to print raw html.

**Comment by tommymonk** [comment] 2019-01-24 18:09
We're now using puppeteer-sharp instead, I believe in this scenario I started using the request interception feature of devtools and made web requests in .net with the knowledge of constructing an absolute URL.

**Comment by abadraja** [comment] 2019-02-05 15:40
Any update on this issue?

**Comment by TimvdLippe** [comment] 2020-04-09 10:43
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!

**Closed by TimvdLippe** 2020-04-09 10:43 UTC
