### ISSUE TITLE
Update license entry to BSD-3-Clause

### ISSUE THREAD

**Issue by lynchbomb** [ChromeDevTools/devtools-protocol#214] opened 2020-04-30 21:11 UTC
https://github.com/ChromeDevTools/devtools-protocol/blob/fb81f45df6d9b0bbe78b593d00882e9a8bbf2a93/package.json#L7

Appears the LICENSE is `BSD-3-Clause` (https://opensource.org/licenses/BSD-3-Clause) yet is marked as a custom license `LicenseRef-LICENSE`.

**Comment by TimvdLippe** [comment] 2020-04-30 23:01
Duplicate of #177 which was changed in #210

Seems like the documentation *does* suggest to use the `SEE LICENSE IN LICENSE` notation (https://docs.npmjs.com/files/package.json). Although I am getting confused as this point, as NPM previously stated that the `LicenseRef-LICENSE` is the appropriate format: https://github.com/npm/npm/issues/8795#issuecomment-119760485

I will have to ask for legal advice if we are allowed to use the BSD-3-Clause identifier instead of our custom reference, but not sure what the timeline on that request is.

**Comment by TimvdLippe** [comment] 2020-05-14 10:31
I received confirmation we are allowed to update our license reference to `BSD-3-Clause`. #215 has the update.

**Closed** 2020-05-15 09:30 UTC

**Comment by lynchbomb** [comment] 2020-05-15 16:06
Thank You!!
